export const coresList = [
  {
    id: "1",
    Name: "Vikas Hembram",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "2",
    Name: "Prabhat Sahu",
    Branch: "",
    Domain: "Sports Coordinators",
  },
  {
    id: "3",
    Name: "Priyesh Tiwari",
    Branch: "",
    Domain: "Sports Coordinators",
  },
  {
    id: "4",
    Name: "Prajwal Dubey",
    Branch: "",
    Domain: "PR and Marketing",
  },

  {
    id: "5",
    Name: "Vivek Kumar",
    Branch: "",
    Domain: "Web Development",
  },
  {
    id: "6",
    Name: " K.S.S Karthik",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "7",
    Name: "  Ayush Tadas",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "8",
    Name: " Swapnil Pandey",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "9",
    Name: " Ayush Bhardwaj",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "10",
    Name: " Aditya Maharishi",
    Branch: "",
    Domain: "Web Development",
  },
  {
    id: "11",
    Name: " Nitesh Keshri",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "12",
    Name: " Prince Kumar Mishra",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "13",
    Name: " Yash Prasad",
    Branch: "",
    Domain: "Event Management",
  },

  {
    id: "14",
    Name: "Hardik Rana",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "15",
    Name: " Ayush Bhavsar",
    Branch: "",
    Domain: " Web Development",
  },
  {
    id: "16",
    Name: " Diksha Manghrani",
    Branch: "Mech",
    Domain: "Design",
  },
  {
    id: "17",
    Name: " Bhoomika Ahuja",
    Branch: "",
    Domain: "PR and marketing",
  },
  {
    id: "18",
    Name: " Chitesh Turkar",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "19",
    Name: " Chitranjan Sahu",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "20",
    Name: " Pratibha Sikheriya",
    Branch: "",
    Domain: "Design",
  },
  {
    id: "21",
    Name: " Devendra Kumar Sahu",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "22",
    Name: " Subrat Shatapathy",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "23",
    Name: " Shreyansh Kumar",
    Branch: "",
    Domain: "Sports Coordinator",
  },

  {
    id: "24",
    Name: "Tanya Zanzad",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "25",
    Name: " Shashank Tiwari",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "26",
    Name: " Nakshatra jindagal",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "27",
    Name: " Vikas Kumar",
    Branch: "",
    Domain: "Documentation",
  },
  {
    id: "28",
    Name: " Yuvraj Chauhan ",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "29",
    Name: " Pratham Pithalia",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "30",
    Name: "Krishna Mishra",
    Branch: "ECE",
    Domain: "Design",
  },
  {
    id: "31",
    Name: "Subhash Malik",
    Branch: "ECE",
    Domain: "Event Management",
  },
  {
    id: "32",
    Name: "Abhilesh Kumar",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "33",
    Name: " Aman Kumar",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "34",
    Name: " Pritesh Kharwal ",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "35",
    Name: "Sparsh Jaggi",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "36",
    Name: "Ravi Shankar Singh",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "37",
    Name: "Sarthak Dubey",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "38",
    Name: "Pranay Dongare",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "39",
    Name: " Ankush Dhobi",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "40",
    Name: "Kalash Jain",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "41",
    Name: "Abhay Sao",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "42",
    Name: "Vicky Sanap",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "43",
    Name: "Deedhit Parihar",
    Branch: "",
    Domain: "Video Editing and Cinematography",
  },
  {
    id: "44",
    Name: "Shailesh Kuamr Sahu",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "45",
    Name: "Tanay Ghatge",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "46",
    Name: "Tushar Kant Sahu",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "47",
    Name: "Shivesh Dwivedi",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "48",
    Name: "Shubhang Upadhyay",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "49",
    Name: "Vivek Kumar Kashyap",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "50",
    Name: "Atul Kumar Vishwakarm",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "51",
    Name: "Rahul Singh",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "52",
    Name: "Hardik Rana",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "53",
    Name: "Aryan Chandra",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "54",
    Name: "Ankush Dhobi",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "55",
    Name: "Akshsay Mairal",
    Branch: "",
    Domain: "Documentation",
  },
  {
    id: "56",
    Name: "Sachin Zade",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "57",
    Name: "Tamsha Tripathi",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "58",
    Name: "Unnati Dewangan",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "59",
    Name: "Shubhang Upadhyay",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "60",
    Name: "Ayushi Barman",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "61",
    Name: "Alka Ragini Gupta",
    Branch: "",
    Domain: "Design",
  },
  {
    id: "62",
    Name: "Sunita Kashyap",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "63",
    Name: "Khyati Thawait",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "64",
    Name: "Sahil Porte",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "65",
    Name: "Sachin Tiwari",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "66",
    Name: "Mayak Kesariya",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "67",
    Name: "Sanagam Singh",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "68",
    Name: "Naveen Patel",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "69",
    Name: "Sarita Otti",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "70",
    Name: "Akhil Deep",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "71",
    Name: "Soumen Mandal",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "72",
    Name: "Pranjaly Singh Kshatriya",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "73",
    Name: "Kaushalendra Kumar",
    Branch: "",
    Domain: "Design",
  },
  {
    id: "74",
    Name: " Siddharth Singh",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "75",
    Name: "Vikas Dewangan",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "76",
    Name: "Anshika Mehra",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "77",
    Name: "Ayush Mishra",
    Branch: "",
    Domain: "Web Development",
  },
  {
    id: "78",
    Name: "Aditya Kumar",
    Branch: "",
    Domain: "Sponsorship",
  },
  {
    id: "79",
    Name: "Anshika Arshi",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "80",
    Name: "Akriti Ravi",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "81",
    Name: "Dheerendra Singh",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "82",
    Name: "Vaibahv Ajgalley",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "83",
    Name: "Adarsh Gaharwar",
    Branch: "",
    Domain: "Event Managament",
  },
  {
    id: "84",
    Name: "Priyanka Kuamri",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "85",
    Name: "Shruti Pandey",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "86",
    Name: "Harshit Pandey",
    Branch: "",
    Domain: "Documentation",
  },
  {
    id: "87",
    Name: "Yash Purohit",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "88",
    Name: "Prajwal Dubey",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "89",
    Name: "Tanya Zanzad",
    Branch: "",
    Domain: "PR and Marketing",
  },
  {
    id: "90",
    Name: "Mohammad Habibur Ral",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "91",
    Name: "Aryan Chandra",
    Branch: "",
    Domain: "Sports Coordinator",
  },
  {
    id: "92",
    Name: "Toy Bhadra",
    Branch: "",
    Domain: "Event Management",
  },
  {
    id: "93",
    Name: "Anupriya Pandey",
    Branch: "",
    Domain: "Spnsorship",
  },
  {
    id: "94",
    Name: "Khushi Hansrajani",
    Branch: "",
    Domain: "Documentation",
  },
];
